/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../../../../../include/jni.h"
/* Header for class Serialization */

#ifndef _Included_Serialization
#define _Included_Serialization
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     Serialization
	 * Method:    getDate
	 * Signature: ()Ljava/lang/String;
	 */
	JNIEXPORT jstring JNICALL Java_Serialization_getDate(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
